default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 'avnadmin'
  port: 22826
  password: 'rp6nrxm0urbtn38k'
  host: 'pg-1ed19a14-lpnu-6077.aivencloud.com'

development:
  <<: *default
  database: defaultdb

test:
  <<: *default
  database: 'defaultdb'

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: 'pg-1ed19a14-lpnu-6077.aivencloud.com'
